name: NestJS-S3 CD

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn Install
        run: yarn
        
      - name: build
        run: yarn build
        
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker image build
      - run: docker build -t eogus2513/image:latest .
      
      - name: docker push
      - run: docker push eogus2513/image
