name: NestJS-S3 CI

on:
  push:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn Install
        run: yarn

      - name: build
        run: yarn build
